// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYrsP7rCiRxWWtp3-TyClMqczX7kgow9g',
    appId: '1:57656144146:web:3e88fcebd85e5a275d83cb',
    messagingSenderId: '57656144146',
    projectId: 'petshop-app-f845c',
    authDomain: 'petshop-app-f845c.firebaseapp.com',
    storageBucket: 'petshop-app-f845c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiewqSx2fHVq7V_KB6htD0tGcpaMJh7xI',
    appId: '1:57656144146:android:c8117e51f0ffa67c5d83cb',
    messagingSenderId: '57656144146',
    projectId: 'petshop-app-f845c',
    storageBucket: 'petshop-app-f845c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbq9BmQfqSS2ndEQwFNDmccbxt0Bu9JJw',
    appId: '1:57656144146:ios:1a54959d19665ac15d83cb',
    messagingSenderId: '57656144146',
    projectId: 'petshop-app-f845c',
    storageBucket: 'petshop-app-f845c.appspot.com',
    iosClientId: '57656144146-4v4pn4a8oef77fub9toat654nppvibl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.petshopAppFlutter',
  );
}
